### ISSUE TITLE
Impossible to restart with a volume

### ISSUE THREAD

**Issue by pleymor** [MaksymBilenko/docker-oracle-12c#120]
Hello,

Thanks for your great work!

I'm able to init a new database with a docker volume, but after a `docker-compose down && docker-compose up -d`, it no longer restarts.

**Error logs with docker-compose logs -f**
```bash
Attaching to oracle_web_1
web_1  | found files in /u01/app/oracle/oradata Using them instead of initial database
web_1  | rm: cannot remove '/u01/app/oracle-product/12.1.0/xe/dbs': Directory not empty
web_1  | found files in /u01/app/oracle/oradata Using them instead of initial database
web_1  | rm: cannot remove '/u01/app/oracle-product/12.1.0/xe/dbs': Directory not empty
...
```

**My docker-compose.yml**
```yml
# cat docker-compose.yml
version: "2"
services:
  web:
    image: sath89/oracle-12c
    restart: always
    ports:
      - '8180:8080'
      - '1521:1521'
    tty: true
    volumes:
      - 'oracle:/u01/app/oracle'
volumes:
  oracle:
```
