### ISSUE TITLE
can't run container - nothing happend, endless restarting atatus

### ISSUE THREAD

**Issue by izharskiy** [MaksymBilenko/docker-oracle-12c#155]
`sath89/oracle-12c   latest    17cd1ab9d9a7   3 years ago    5.7GB`

```
root@app:~# docker ps
CONTAINER ID   IMAGE                      COMMAND             CREATED         STATUS                          PORTS     NAMES
195c5a31e3b2   sath89/oracle-12c:latest   "/entrypoint.sh "   8 minutes ago   Restarting (1) 59 seconds ago             oradb-bank

```

```
docker version
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
VERSION="20.04.2 LTS (Focal Fossa)"
```

```
# uname -a
Linux app 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by izharskiy** [comment]
My `compose.yaml`

```
version: '3.9'
services:
    oradb-bank:
        image: sath89/oracle-12c:latest
        container_name: oradb-bank
        # copy-paste https://github.com/MaksymBilenko/docker-oracle-12c/issues/61#issue-255849917
        healthcheck:
            test: ["CMD-SHELL", "if [ \"`echo \\\"SELECT ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME = 'ANONYMOUS' AND ACCOUNT_STATUS = 'EXPIRED';\\\"|/u01/app/oracle/product/12.1.0/xe/bin/sqlplus -S sys/oracle as sysdba|grep ACCOUNT_STATUS`\" = \"ACCOUNT_STATUS\" ];then true;else false;fi"]
            timeout: 3s
            interval: 30s
            # start_period: 900s
            retries: 30        
        restart: always
        ports:
            - "8080:8080"
            - "1521:1521"
        volumes:
            - /mnt/oracle/data:/u01/app/oracle
    app-centos-bank:
        image: 03709227889e
        container_name: app-bank
        privileged: true
        # https://github.com/compose-spec/compose-spec/blob/master/spec.md#long-syntax-1
        depends_on: 
            oradb-bank:
                condition: service_healthy
```
