### ISSUE TITLE
Include Healthcheck

### ISSUE THREAD

**Issue by mgansler** [MaksymBilenko/docker-oracle-12c#61]
It would be nice for the container to have a health status.
Here is what I have come up with in compose, but maybe there is a better way and I think it would be great to have the healthcheck included in the image itself.

```yaml
services:
  database:
    image: sath89/oracle-12c:r1
    healthcheck:
      test: ["CMD-SHELL", "if [ \"`echo \\\"SELECT ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME = 'ANONYMOUS' AND ACCOUNT_STATUS = 'EXPIRED';\\\"|/u01/app/oracle/product/12.1.0/xe/bin/sqlplus -S sys/oracle as sysdba|grep ACCOUNT_STATUS`\" = \"ACCOUNT_STATUS\" ];then true;else false;fi"]
      timeout: 3s
      interval: 30s
      # start_period: 900s
      retries: 30
```

"start_period" is commented out because https://github.com/docker/cli/pull/475 has been merged but not released yet so compose doesn't support it (yet). "interval" and "retries" can be modified.
